apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-chatbot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/banking-chatbot
    repoURL: https://github.com/Newbigfonsz/banking-chatbot-k8s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
