apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-chatbot-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>SecureBank AI Assistant</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }
            .chat-container {
                width: 400px;
                height: 600px;
                background: white;
                border-radius: 20px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                display: flex;
                flex-direction: column;
                overflow: hidden;
            }
            .chat-header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 20px;
                text-align: center;
            }
            .bank-logo { font-size: 22px; font-weight: bold; }
            .quick-actions {
                padding: 10px;
                background: white;
                display: flex;
                gap: 8px;
                overflow-x: auto;
            }
            .quick-action {
                padding: 8px 12px;
                background: #f0f0f0;
                border: none;
                border-radius: 15px;
                font-size: 12px;
                cursor: pointer;
                white-space: nowrap;
            }
            .quick-action:hover {
                background: #667eea;
                color: white;
            }
            .chat-messages {
                flex: 1;
                overflow-y: auto;
                padding: 15px;
                background: #f8f9fa;
            }
            .message {
                max-width: 80%;
                padding: 12px;
                border-radius: 16px;
                margin-bottom: 10px;
                animation: fadeIn 0.3s;
            }
            @keyframes fadeIn {
                from { opacity: 0; transform: translateY(5px); }
                to { opacity: 1; transform: translateY(0); }
            }
            .user-message {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                margin-left: auto;
            }
            .bot-message {
                background: white;
                color: #333;
                box-shadow: 0 2px 5px rgba(0,0,0,0.1);
                white-space: pre-wrap;
            }
            .chat-input-container {
                padding: 15px;
                background: white;
                border-top: 1px solid #e0e0e0;
                display: flex;
                gap: 10px;
            }
            .chat-input {
                flex: 1;
                padding: 12px;
                border: 2px solid #e0e0e0;
                border-radius: 25px;
                outline: none;
                font-size: 14px;
            }
            .chat-input:focus {
                border-color: #667eea;
            }
            .send-button {
                width: 45px;
                height: 45px;
                border-radius: 50%;
                border: none;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                cursor: pointer;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 18px;
            }
            .send-button:hover {
                transform: scale(1.05);
            }
        </style>
    </head>
    <body>
        <div class="chat-container">
            <div class="chat-header">
                <div class="bank-logo">🏦 SecureBank AI</div>
                <div>Your 24/7 Banking Assistant</div>
            </div>
            
            <div class="quick-actions">
                <button class="quick-action" onclick="quickSend('Check balance')">💰 Balance</button>
                <button class="quick-action" onclick="quickSend('Recent transactions')">📊 History</button>
                <button class="quick-action" onclick="quickSend('Transfer money')">💸 Transfer</button>
                <button class="quick-action" onclick="quickSend('Help')">❓ Help</button>
            </div>
            
            <div class="chat-messages" id="chatMessages">
                <div class="bot-message">👋 Welcome to SecureBank!

🚀 This chatbot is running on:
- Kubernetes (6-node cluster)
- AWS serverless backend
- GitOps via ArgoCD

Try the buttons above or type a message!</div>
            </div>
            
            <div class="chat-input-container">
                <input type="text" class="chat-input" id="chatInput" placeholder="Type your message..." />
                <button class="send-button" onclick="sendMsg()">➤</button>
            </div>
        </div>

        <script>
            const API_URL = 'https://4c1vpuut91.execute-api.us-east-1.amazonaws.com/dev/chat';
            const sessionId = 'demo-' + Date.now();
            
            const input = document.getElementById('chatInput');
            const messagesDiv = document.getElementById('chatMessages');
            
            input.addEventListener('keypress', function(e) {
                if (e.key === 'Enter') sendMsg();
            });
            
            function addMsg(text, isUser) {
                const msg = document.createElement('div');
                msg.className = 'message ' + (isUser ? 'user-message' : 'bot-message');
                msg.textContent = text;
                messagesDiv.appendChild(msg);
                messagesDiv.scrollTop = messagesDiv.scrollHeight;
            }
            
            async function sendMsg() {
                const message = input.value.trim();
                if (!message) return;
                
                addMsg(message, true);
                input.value = '';
                
                // Demo responses for the platform demonstration
                let response = "I'm your banking assistant! ";
                if (message.toLowerCase().includes('balance')) {
                    response = "💰 Your current balance is $5,432.10\n\n✅ Running on AWS Lambda + Kubernetes";
                } else if (message.toLowerCase().includes('transfer')) {
                    response = "💸 To transfer funds, please specify:\n• Amount\n• Destination account\n\n🚀 Powered by serverless architecture";
                } else if (message.toLowerCase().includes('help')) {
                    response = "🤝 I can help with:\n• Balance inquiries\n• Fund transfers\n• Transaction history\n• Account information\n\n⚡ Enterprise platform: K8s + AWS + GitOps";
                } else {
                    response += "This demo showcases:\n• Professional banking UI\n• Kubernetes deployment\n• AWS integration ready\n• Complete DevOps pipeline";
                }
                
                setTimeout(() => addMsg(response, false), 500);
            }
            
            function quickSend(text) {
                input.value = text;
                sendMsg();
            }
            
            window.onload = () => input.focus();
        </script>
    </body>
    </html>
