apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-chatbot-html
data:
  index.html: |
    <!DOCTYPE html>
    <html><head><title>SecureBank AI</title></head>
    <body><h1>Banking Chatbot - GitOps Working!</h1>
    <p>Professional banking interface deployed via ArgoCD.</p></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-chatbot
  template:
    metadata:
      labels:
        app: banking-chatbot
    spec:
      containers:
      - name: banking-chatbot
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: banking-chatbot-html
---
apiVersion: v1
kind: Service
metadata:
  name: banking-chatbot-svc
spec:
  selector:
    app: banking-chatbot
  ports:
  - port: 80
    targetPort: 80
