apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-chatbot-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SecureBank AI Assistant</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                height: 100vh; display: flex; justify-content: center; align-items: center;
            }
            .chat-container {
                width: 420px; height: 650px; background: white; border-radius: 20px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.3); display: flex; flex-direction: column; overflow: hidden;
            }
            .chat-header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white; padding: 18px; text-align: center;
            }
            .bank-logo { font-size: 22px; font-weight: bold; margin-bottom: 4px; }
            .quick-actions {
                padding: 10px; background: white; display: flex; gap: 6px; overflow-x: auto;
            }
            .quick-action {
                padding: 6px 12px; background: #f0f0f0; border: none; border-radius: 15px;
                font-size: 11px; cursor: pointer; white-space: nowrap; transition: all 0.2s;
            }
            .quick-action:hover { background: #667eea; color: white; }
            .chat-messages {
                flex: 1; overflow-y: auto; padding: 15px; background: #f8f9fa; min-height: 0;
            }
            .message {
                max-width: 85%; padding: 10px 14px; border-radius: 16px; margin-bottom: 12px;
                animation: fadeIn 0.3s;
            }
            @keyframes fadeIn { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }
            .user-message {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white; margin-left: auto; border-bottom-right-radius: 4px;
            }
            .bot-message {
                background: white; color: #333; box-shadow: 0 2px 5px rgba(0,0,0,0.08);
                white-space: pre-wrap; border-bottom-left-radius: 4px; line-height: 1.4; font-size: 14px;
            }
            .chat-input-container {
                padding: 15px; background: white; border-top: 1px solid #e0e0e0;
                display: flex; gap: 10px; flex-shrink: 0;
            }
            .chat-input {
                flex: 1; padding: 10px 15px; border: 2px solid #e0e0e0; border-radius: 25px;
                outline: none; font-size: 14px; transition: border-color 0.2s;
            }
            .chat-input:focus { border-color: #667eea; }
            .send-button {
                width: 42px; height: 42px; border-radius: 50%; border: none;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white; cursor: pointer; display: flex; align-items: center; justify-content: center;
                transition: transform 0.2s; font-size: 18px;
            }
            .send-button:hover { transform: scale(1.05); }
        </style>
    </head>
    <body>
        <div class="chat-container">
            <div class="chat-header">
                <div class="bank-logo">🏦 SecureBank AI</div>
                <div>Your 24/7 Banking Assistant</div>
            </div>
            <div class="quick-actions">
                <button class="quick-action" onclick="quickSend('Check balance')">💰 Balance</button>
                <button class="quick-action" onclick="quickSend('Recent transactions')">📊 Transactions</button>
                <button class="quick-action" onclick="quickSend('Transfer money')">💸 Transfer</button>
                <button class="quick-action" onclick="quickSend('Find ATM')">📍 ATM</button>
                <button class="quick-action" onclick="quickSend('Help')">❓ Help</button>
            </div>
            <div class="chat-messages" id="chatMessages">
                <div class="bot-message">👋 Welcome to SecureBank! 

🚀 This banking chatbot is running on:
- Kubernetes cluster (6 nodes)
- AWS serverless backend
- GitOps deployment via ArgoCD

Try asking about your balance or click any quick action above!</div>
            </div>
            <div class="chat-input-container">
                <input type="text" class="chat-input" id="chatInput" placeholder="Type your message..." autocomplete="off" />
                <button class="send-button" onclick="sendMsg()">➤</button>
            </div>
        </div>

        <script>
            // Connect to your AWS API Gateway
            const API_URL = 'https://4c1vpuut91.execute-api.us-east-1.amazonaws.com/dev/chat';
            const sessionId = 'session-' + Date.now();
            
            const input = document.getElementById('chatInput');
            const messagesDiv = document.getElementById('chatMessages');
            
            input.addEventListener('keypress', function(e) {
                if (e.key === 'Enter') sendMsg();
            });
            
            function addMsg(text, isUser) {
                const msg = document.createElement('div');
                msg.className = 'message ' + (isUser ? 'user-message' : 'bot-message');
                msg.textContent = text;
                messagesDiv.appendChild(msg);
                messagesDiv.scrollTop = messagesDiv.scrollHeight;
            }
            
            async function sendMsg() {
                const message = input.value.trim();
                if (!message) return;
                
                addMsg(message, true);
                input.value = '';
                input.focus();
                
                try {
                    const response = await fetch(API_URL, {
                        method: 'POST',
                        headers: {'Content-Type': 'application/json'},
                        body: JSON.stringify({message: message, sessionId: sessionId})
                    });
                    
                    const data = await response.json();
                    addMsg(data.response, false);
                } catch (error) {
                    addMsg('Connected to Kubernetes demo. Full AWS backend integration available.', false);
                }
            }
            
            function quickSend(text) {
                input.value = text;
                sendMsg();
            }
            
            window.onload = () => input.focus();
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-chatbot
  template:
    metadata:
      labels:
        app: banking-chatbot
    spec:
      containers:
      - name: banking-chatbot
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: banking-chatbot-html
---
apiVersion: v1
kind: Service
metadata:
  name: banking-chatbot-svc
spec:
  selector:
    app: banking-chatbot
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking-http-only
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: banking.alphonzojonesjr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: banking-chatbot-svc
            port:
              number: 80
