apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-chatbot-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SecureBank AI Assistant</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }
            .sr-only {
                position: absolute;
                width: 1px;
                height: 1px;
                padding: 0;
                margin: -1px;
                overflow: hidden;
                clip: rect(0, 0, 0, 0);
                white-space: nowrap;
                border: 0;
            }
            .chat-container {
                width: 100%;
                height: 100vh;
                background: white;
                display: flex;
                flex-direction: column;
                overflow: hidden;
                animation: slideUp 0.5s ease-out;
            }
            @media (min-width: 520px) {
                .chat-container {
                    width: 480px;
                    max-height: 700px;
                    height: 90vh;
                    border-radius: 20px;
                    box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                }
            }
            @keyframes slideUp {
                from { transform: translateY(30px); opacity: 0; }
                to { transform: translateY(0); opacity: 1; }
            }
            .chat-header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 18px;
                text-align: center;
            }
            .bank-logo { font-size: 22px; font-weight: bold; margin-bottom: 4px; }
            .header-subtitle { font-size: 13px; opacity: 0.9; }
            .quick-actions {
                padding: 10px;
                background: white;
                display: flex;
                gap: 6px;
                overflow-x: auto;
                border-bottom: 1px solid #e0e0e0;
                -webkit-overflow-scrolling: touch;
            }
            .quick-action {
                padding: 6px 12px;
                background: #f0f0f0;
                border: none;
                border-radius: 15px;
                font-size: 12px;
                cursor: pointer;
                white-space: nowrap;
                transition: background 0.2s, color 0.2s, transform 0.2s;
            }
            .quick-action:hover {
                background: #667eea;
                color: white;
                transform: translateY(-1px);
            }
            .quick-action:focus-visible {
                outline: 3px solid #667eea;
                outline-offset: 2px;
            }
            .chat-messages {
                flex: 1;
                overflow-y: auto;
                padding: 15px;
                background: #f8f9fa;
                min-height: 0;
                scroll-behavior: smooth;
            }
            .message {
                max-width: 85%;
                padding: 10px 14px;
                border-radius: 16px;
                margin-bottom: 12px;
                animation: fadeIn 0.3s;
            }
            @keyframes fadeIn {
                from { opacity: 0; transform: translateY(5px); }
                to { opacity: 1; transform: translateY(0); }
            }
            .user-message {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                margin-left: auto;
                border-bottom-right-radius: 4px;
            }
            .bot-message {
                background: white;
                color: #333;
                box-shadow: 0 2px 5px rgba(0,0,0,0.08);
                white-space: pre-wrap;
                border-bottom-left-radius: 4px;
                line-height: 1.5;
                font-size: 14px;
            }
            .message-time {
                font-size: 10px;
                opacity: 0.5;
                margin-top: 4px;
            }
            .user-message .message-time { text-align: right; }
            .bot-message .message-time { text-align: left; }
            .typing-indicator {
                display: flex;
                gap: 4px;
                padding: 12px 16px;
                background: white;
                border-radius: 16px;
                border-bottom-left-radius: 4px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.08);
                margin-bottom: 12px;
                width: fit-content;
                animation: fadeIn 0.3s;
            }
            .typing-indicator span {
                width: 8px;
                height: 8px;
                background: #667eea;
                border-radius: 50%;
                animation: typingBounce 1.4s infinite ease-in-out both;
            }
            .typing-indicator span:nth-child(1) { animation-delay: -0.32s; }
            .typing-indicator span:nth-child(2) { animation-delay: -0.16s; }
            .typing-indicator span:nth-child(3) { animation-delay: 0s; }
            @keyframes typingBounce {
                0%, 80%, 100% { transform: scale(0.6); opacity: 0.4; }
                40% { transform: scale(1); opacity: 1; }
            }
            .error-message {
                background: #fff3f3;
                color: #d32f2f;
                border: 1px solid #ffcdd2;
                padding: 10px 14px;
                border-radius: 16px;
                margin-bottom: 12px;
                font-size: 13px;
                animation: fadeIn 0.3s;
            }
            .chat-input-container {
                padding: 15px;
                background: white;
                border-top: 1px solid #e0e0e0;
                display: flex;
                gap: 10px;
            }
            .chat-input {
                flex: 1;
                padding: 10px 15px;
                border: 2px solid #e0e0e0;
                border-radius: 25px;
                outline: none;
                font-size: 14px;
                transition: border-color 0.2s;
            }
            .chat-input:focus { border-color: #667eea; }
            .chat-input:focus-visible {
                outline: 3px solid #667eea;
                outline-offset: 2px;
            }
            .chat-input:disabled {
                background: #f5f5f5;
                color: #999;
            }
            .send-button {
                width: 42px;
                height: 42px;
                border-radius: 50%;
                border: none;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                cursor: pointer;
                display: flex;
                align-items: center;
                justify-content: center;
                transition: transform 0.2s;
                font-size: 18px;
            }
            .send-button:hover { transform: scale(1.05); }
            .send-button:focus-visible {
                outline: 3px solid #667eea;
                outline-offset: 2px;
            }
            .send-button:disabled {
                opacity: 0.5;
                cursor: not-allowed;
                transform: none;
            }
        </style>
    </head>
    <body>
        <div class="chat-container">
            <header class="chat-header" role="banner">
                <div class="bank-logo">SecureBank AI</div>
                <div class="header-subtitle">Your 24/7 Banking Assistant</div>
            </header>
            <nav class="quick-actions" role="navigation" aria-label="Quick actions">
                <button class="quick-action" onclick="quickSend('Check balance')" aria-label="Check balance">Balance</button>
                <button class="quick-action" onclick="quickSend('Recent transactions')" aria-label="Recent transactions">Transactions</button>
                <button class="quick-action" onclick="quickSend('Transfer money')" aria-label="Transfer money">Transfer</button>
                <button class="quick-action" onclick="quickSend('Find ATM')" aria-label="Find nearby ATM">ATM</button>
                <button class="quick-action" onclick="quickSend('Help')" aria-label="Get help">Help</button>
            </nav>
            <main class="chat-messages" id="chatMessages" role="log" aria-live="polite" aria-label="Chat messages">
                <div class="message bot-message">
                    <div class="message-content">Welcome to SecureBank! How can I help you today?

    Try asking about your balance, recent transactions, or click any quick action above.</div>
                </div>
            </main>
            <span id="statusAnnouncer" class="sr-only" role="status" aria-live="assertive"></span>
            <div class="chat-input-container" role="form" aria-label="Message input">
                <label for="chatInput" class="sr-only">Type your message</label>
                <input type="text" class="chat-input" id="chatInput" placeholder="Type your message..." autocomplete="off" aria-label="Type your message" />
                <button class="send-button" id="sendButton" onclick="sendMsg()" aria-label="Send message">&#10148;</button>
            </div>
        </div>
        <script>
            var API_URL = 'https://4c1vpuut91.execute-api.us-east-1.amazonaws.com/dev/chat';
            var sessionId = 'session-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
            var input = document.getElementById('chatInput');
            var messagesDiv = document.getElementById('chatMessages');
            var sendBtn = document.getElementById('sendButton');
            var announcer = document.getElementById('statusAnnouncer');

            input.addEventListener('keypress', function(e) {
                if (e.key === 'Enter' && !sendBtn.disabled) sendMsg();
            });

            function formatTime() {
                var now = new Date();
                return now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
            }

            function addMsg(text, isUser) {
                var msg = document.createElement('div');
                msg.className = 'message ' + (isUser ? 'user-message' : 'bot-message');
                var content = document.createElement('div');
                content.className = 'message-content';
                content.textContent = text;
                msg.appendChild(content);
                var time = document.createElement('div');
                time.className = 'message-time';
                time.textContent = formatTime();
                msg.appendChild(time);
                messagesDiv.appendChild(msg);
                messagesDiv.scrollTop = messagesDiv.scrollHeight;
            }

            function addErrorMsg(text) {
                var msg = document.createElement('div');
                msg.className = 'error-message';
                msg.setAttribute('role', 'alert');
                msg.textContent = text;
                messagesDiv.appendChild(msg);
                messagesDiv.scrollTop = messagesDiv.scrollHeight;
            }

            function showTyping() {
                var el = document.createElement('div');
                el.className = 'typing-indicator';
                el.id = 'typingIndicator';
                el.setAttribute('role', 'status');
                el.setAttribute('aria-label', 'Assistant is typing');
                el.innerHTML = '<span></span><span></span><span></span>';
                messagesDiv.appendChild(el);
                messagesDiv.scrollTop = messagesDiv.scrollHeight;
            }

            function hideTyping() {
                var el = document.getElementById('typingIndicator');
                if (el) el.remove();
            }

            function getDemoResponse(message) {
                var msg = message.toLowerCase();
                if (msg.includes('balance')) {
                    return "Your Account Balances:\n\nChecking ****1234: $5,432.10\nSavings ****5678: $15,750.25\nCredit ****9012: $2,340.50 available";
                } else if (msg.includes('transfer')) {
                    return "Let's set up your transfer.\n\nPlease provide:\n- Amount (e.g. $100)\n- Destination account number\n\nAll transfers are secured with 2-factor authentication.";
                } else if (msg.includes('transaction')) {
                    return "Recent Transactions:\n\nToday: Starbucks -$5.85\nYesterday: Direct Deposit +$3,500.00\nFeb 13: Amazon -$67.42\nFeb 12: Electric Bill -$142.30\n\nCurrent Balance: $5,432.10";
                } else if (msg.includes('atm') || msg.includes('location')) {
                    return "Nearby ATMs:\n\n1. 123 Main St (0.3 mi)\n2. 456 Oak Ave (0.7 mi)\n3. 789 Pine Rd (1.2 mi)\n\nAll ATMs are fee-free for SecureBank customers.";
                } else if (msg.includes('help')) {
                    return "I can help with:\n\n- Check account balances\n- View recent transactions\n- Transfer money between accounts\n- Find nearby ATMs\n- Pay bills\n\nJust type your question or use the quick actions above!";
                } else {
                    return 'You said: "' + message + '"\n\nI can help with balance inquiries, transactions, transfers, and more. Try asking about your balance!';
                }
            }

            async function sendMsg() {
                var message = input.value.trim();
                if (!message) return;

                sendBtn.disabled = true;
                input.disabled = true;
                announcer.textContent = 'Processing your message';

                addMsg(message, true);
                input.value = '';
                showTyping();

                try {
                    var response = await fetch(API_URL, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ message: message, sessionId: sessionId })
                    });
                    var data = await response.json();
                    hideTyping();
                    addMsg(data.response || data.body || 'Response received.', false);
                } catch (error) {
                    hideTyping();
                    if (!navigator.onLine) {
                        addErrorMsg('You appear to be offline. Showing demo responses.');
                    }
                    addMsg(getDemoResponse(message), false);
                }

                sendBtn.disabled = false;
                input.disabled = false;
                input.focus();
                announcer.textContent = 'Response received';
            }

            function quickSend(text) {
                input.value = text;
                sendMsg();
            }

            window.onload = function() { input.focus(); };
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-chatbot
  template:
    metadata:
      labels:
        app: banking-chatbot
    spec:
      securityContext:
        fsGroup: 101
      containers:
      - name: banking-chatbot
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            - CHOWN
            - SETUID
            - SETGID
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: html-content
        configMap:
          name: banking-chatbot-html
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: banking-chatbot-svc
spec:
  selector:
    app: banking-chatbot
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: banking-chatbot-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: banking-chatbot
